version: '3'

# services:
#   rstudio:
#     image: ${IMAGE_RAW}
#     container_name: rstudio
#     build:
#       context: .
#       args:
#         IMAGE: ${IMAGE_RAW}
#         TINYTEX_VERSION: ${TINYTEX_VERSION}
#         TINYTEX_VINTAGE: ${TINYTEX_VINTAGE}
#         WORKDIR: ${PROJECT_PATHS_CONTAINER}
#     networks:
#       - default
#     volumes:
#       - ${MOUNT_PROJECT}
#     ports:
#       - ${PORT_MAP}
#     environment:
#       - 'DISABLE_AUTH=${DISABLE_AUTH}'
#       - 'ROOT=${ROOT}'

# networks:
#   default:
#     driver: bridge

services:
  rstudio:
    image: bautheac/versytex:4.1-2021.12
    networks:
      - default
    volumes:
      - .:/home/rstudio/project
    ports:
      - 8787:8787
    environment:
      - 'DISABLE_AUTH=true'
      - 'ROOT=true'

networks:
  default:
    driver: bridge
