---
title: "Financialisation of Commodity Markets"
subtitle: "Co-movement Behind-the-scenes"
format: pdf
bibliography: literature_files/references.bib
---

```{r globals, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

# folder <- "literature_files"; dir.create(folder); path <- paste(folder, "references.bib", sep = "/")
# download.file("https://www.dropbox.com/s/htnd7o9nnkk8ng8/references.bib?dl=1", path)

```

Dear Editor-in-Chief and the Journal of Futures Markets Editorial Board,  
  \
I am pleased to submit our manuscript titled "Financialisation of Commodity Markets: Co-movement Behind-the-scenes" for consideration for publication in the Journal of Futures Markets.
  \
  \
Our paper advances the ongoing debates in the Journal of Futures Markets by providing an alternative examination of the financialisation of commodity markets which serves as a unique contribution to the literature. Specifically, our research extends the dialogue on the impact of the phenomenon on various aspects of the commodity complex including on co-movement and market integration, both within the commodity space [@liu_analyzing_2021; @sehgal_who_2021; @yang_volatility_2021; @gong_time_2022] and with legacy asset classes [@conghui_liquidity_2020; @isleimeyyeh_role_2020; @daskalaki_new_2021; @han_trend_2022; @saishree_exploring_2022]; on market fundamentals [@isleimeyyeh_role_2020; @marechal_tale_2020; @yin_intermediary_2021], particularly risk transfer [@ahmadi_theory_2020] and price formation [@adammer_price_2018; @merkoulova_predictive_2020; @kupabado_financialisation_2021; @sehgal_who_2021]; as well as on investment in the sector [@daskalaki_new_2021; @han_trend_2022]. The paper also addresses the consequences of financialisation from a regulatory perspective, effectively contributing to the debate on futures markets oversight: @janardanan_commodity_2019, @fan_untold_2020, @hu_impact_2020, @mixon_us_2022, @szabo_margin_2022. Additionally, our study further extends the collection of recent seminal works that study financialisation using asset pricing techniques [@fan_untold_2020; @marechal_tale_2020; @yin_intermediary_2020; @han_trend_2022]. More generally, the paper provides an empirical complement to the growing body of research on co-movement and market integration within the commodity complex [@xiao_estimating_2020; @yang_return_2020; @luo_how_2021; @prokopczuk_dynamics_2021; @deBoer_intraday_2022; @dhaene_volatility_2022; @zhang_impact_2022] and beyond [@alquist_effect_2020; @kang_commodity_2020; @wong_impact_2020; @dark_lead_2021; @li_forecasting_2021; @liu_does_2022; @ming_contagion_2022; @zhang_do_2022; @zhang_influence_2023]; on commodity market fundamentals [@brooks_samuelson_2020; @llorente_trading_2020; @marechal_do_2021; @li_hedging_2022] including risk transfer [@fan_speculative_2020; @oglend_futures_2020; @huang_good_2023] and price formation [@bohmann_price_2019; @janardanan_commodity_2019; @arroyo_old_2020; @bohl_return_2020; @frino_sensitivity_2020; @siklos_metal_2020; @andersen_efficiency_2021; @figuerola_oil_2021; @geyer_determinants_2021; @gilbert_regional_2021; @yang_price_2021; @fuertes_risk_2022; @li_robust_2022; @bandyopadhyay_impact_2023; @chen_temperature_2023; @fan_wisdom_2023; @filippidis_evaluating_2023]; and on asset pricing in the context of commodity markets [@kang_commodity_2020; @yuan_pobability_2023].  
  \
Drawing upon the issues and methods discussed in these studies, our research provides a broader perspective on the phenomenon of financialisation by examining its effects on a large cross-section of liquid commodities, rather than focusing on individual markets. This approach allows us to capture the global nature of financialisation and its influence on market fundamentals, an area of research that we believed has not yet been fully explored. We argue that the global nature of the phenomenon makes cross-sectional co-movement a cornerstone issue and we provide new insights into this issue through our novel approach, using a bespoke futures-based asset pricing framework. We view this contribution as important because it helps to deepen our understanding of the consequences of financialisation for commodity markets and provides a more nuanced perspective on the debates about the phenomenon. We further believe this understanding is beneficial for regulator, policymakers and investors in shaping risk management practices and investment strategies in the age of heightened market participation.  
  \
If published, we believe that this paper will be cited for its innovative approach to studying the phenomenon of commodity markets financialisation. The paper challenges the conventional focus on individual markets and instead emphasises the importance of considering the global and cross-sectional impact of financialisation. Our results provide compelling evidence that the phenomenon had ontological consequences for the commodity complex, offering a key reference for future studies on financialisation and commodity markets. By further emphasising the regulatory implications of financialisation, our study also contributes to the discourse on futures markets oversight, offering an additional strong reference point.
  \
  \
The manuscript is original, has not been submitted elsewhere, and all the authors have approved it for submission to your journal. There are no conflicts of interest to declare.  
  \
We look forward to the possibility of our paper being published in the Journal of Futures Markets and contributing to the ongoing debates in this field.  
  \
Thank you for considering our submission.
  \
  \
Best regards,  
  \
Devraj Basu, Olivier Bauthéac

\pagebreak

## References
